version: 1

formatters:
  default:
    format: "[%(asctime)s] %(name)-10s %(filename)s[LINE:%(lineno)d] %(levelname)-8s %(message)s"

handlers:
  console:
    class: "logging.StreamHandler"
    formatter: "default"
    stream: "ext://sys.stdout"

  main-file: &main-file
    class: "logging.handlers.RotatingFileHandler"
    formatter: "default"
    filename: "main.log"
    encoding: "utf-8"
    backupCount: 5
    maxBytes: 10000000

  main2-file:
    <<: *main-file
    filename: "main2.log"

loggers:
  main:
    handlers: ["console", "main-file"]
    level: "DEBUG"

  main2:
    handlers: ["console", "main2-file"]
    level: "INFO"
